apiVersion: v1
kind: Service
metadata:
  name: tsp-nodezoom
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: tsp-nodezoom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsp-nodezoom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tsp-nodezoom
  template:
    metadata:
      labels:
        app: tsp-nodezoom
    spec:
      containers:
      - name: tsp-nodezoom
        image: aanuoluwapoakinyera/node-zoom:latest
        ports:
        - containerPort: 3000
        env:
        - name: MESSAGE
          value: Hello from my first K8s deployment!
